server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://115.159.206.62:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true
      password: 123456