server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://115.159.206.62:3306/foodie-shop-dev?useUnicode=false&characterEncoding=UTF-8&autoReconnect=true
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl